config/routes.rb
Rails.application.routes.draw do

 root to: "sessions#new"

 get "main", to: "main#index"

 get "adduser", to: "adduser#new"
 post "adduser", to: "adduser#create"

 get "login", to: "sessions#new"
 post "login", to: "sessions#create"

 delete "logout", to:"sessions#destroy"

 get "shodan", to: "shodan#index"

 get "search", to: "search#search"
 
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :username, presence: true
    validates_uniqueness_of :username
end

app/controllers/adduser_controller.rb
class AdduserController < ApplicationController
    def new
        @user = User.new
    end
    def create 
       @user = User.new(user_params)
       if @user.save
            #session[:user_id] = @user.id 
            redirect_to adduser_path, notice: "successfully created account"
       else
            
           redirect_to adduser_path, notice: "already exists"
       end

    end

    private
    def user_params
        params.require(:user).permit(:username, :password)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
     
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
    def index
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
       if session[:user_id]
            @user =User.find_by(id: session[:user_id])
       else
            redirect_to login_path
        end
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
    def search
        @ip = params[:IP]
        searchbyIP(@ip)

    end
    private
    def request_api(url,ip)
      connection = Excon.new(url)
      @response = connection.get(:path =>"/shodan/host/#{ip}?key=wpNOZqfwixQdaeTiKTQeIyePU7XSymm2")
      return nil if @response.status != 200
      @city =JSON.parse(@response.body)["city"]
      @region_code =JSON.parse(@response.body)["region_code"]
      @isp =JSON.parse(@response.body)["isp"]
      @ports =JSON.parse(@response.body)["ports"]
      @hostnames =JSON.parse(@response.body)["hostnames"]
      @country_code=JSON.parse(@response.body)["country_code"]
      @country_name =JSON.parse(@response.body)["country_name"]
      @domains =JSON.parse(@response.body)["domains"]
      @ip_str =JSON.parse(@response.body)["ip_str"]
    
    end
    def searchbyIP(ip)
      request_api("https://api.shodan.io",ip)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < AdduserController
    def destroy
        session[:user_id] = nil
        redirect_to login_path, notice: "logged out"
    end

    def new

    end

    def create
        user = User.find_by(username: params[:username])

        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id
            if user.username == "admin"
                redirect_to main_path, notice: "logged in successfully"
            else 
                redirect_to shodan_path, notice: "logged in successfully"
            end
        else
            flash[:alert] = "Invalid username or password"
            render :new
        end
    end
end

app/controllers/shodan_controller.rb
class ShodanController < ApplicationController
 def index 
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/adduser/new.html.erb
  <nav class="navbar navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="/adduser"> Add user</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/shodan"> Shodan</a>
            </li>
          </ul>
        </div>
      </div>
  </nav>

  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card bg-dark text-white" style="border-radius: 1rem;">
          <div class="card-body p-5 text-center">

            <div class="mb-md-5 mt-md-4 pb-5">

              <h2 class="fw-bold mb-2 text-uppercase"> Add User</h2>
              <p class="text-white-50 mb-5">Here The Admin can add a user</p>
                <%= form_with model: @user, url: adduser_path do |form|%>

              <div class="form-outline form-white mb-4">
                <%= form.label :username ,class: "form-label"%>
                <%= form.text_field :username, class: "form-control form-control-lg" , placeholder: "username" %>
              </div>

              <div class="form-outline form-white mb-4">
                <%= form.label :password %>
                <%= form.password_field :password,class: "form-control form-control-lg" , placeholder: "password" %>
              </div>
                 <%= form.submit "Add User" ,class: "btn btn-outline-light btn-lg px-5" %> 
                <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shodanapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href= "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel= "stylesheet" >
    <script src= "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

  <div class="container">
    <%= yield %>
    
    <% flash.each do |type, msg| %>
      <div>
        <%= msg %>
      </div>
    <% end %>

 </div>
  </body>
  
</html>

app/views/login/index.html.erb
<div class="d-flex align-items justify-content">
    <h1> Login Page</h1>
</div>

app/views/main/index.html.erb
<% if @user.username == "admin" %>
  <nav class="navbar navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="/adduser"> Add user</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/shodan"> Shodan</a>
            </li>
          </ul>
        </div>
      </div>
  </nav>
<% end %>

<% if @user %>
<div class="note note-light mb-3">
  <strong>Logged in as: </strong> <%= @user.username %>
</div>
     
     <%= button_to "Logout", logout_path, method: :delete ,class: "btn btn-primary"%>
<% end %>

app/views/search/search.html.erb
<ul class="list-group">
<h1 >
    <%= @ip_str%>
</h1>
  <li class="list-group-item">City:
    <%= @city%> 
  </li>
  <li class="list-group-item">Region Code:
    <%= @region_code%> 
  </li>
  <li class="list-group-item">ISP:
    <%= @isp%>
  </li>
  <li class="list-group-item">Ports:
    <%= @ports%>
  </li>
  <li class="list-group-item">Hostnames:
    <%= @hostnames%> 
  </li>
  <li class="list-group-item">Country Code:
    <%= @country_code%> 
  </li>
   <li class="list-group-item">Country Name:
    <%= @country_code%> 
  </li>
  <li class="list-group-item">Domains:
    <%= @domains%> 
  </li>
  
</ul>

app/views/shodan/index.html.erb
<div class="container py-5 h-100">

    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
     
          <div class="card-body p-5 text-center">
          <h1>Shodan</h1>
          
            <div class="mb-md-5 mt-md-4 pb-5">           
        
            <%= form_with url: search_path, method: 'get', local: true do |form| %>

              <div class="form-outline form-white mb-4">
                <strong>
                <%= form.label 'Search for IP '%>
                </strong>
                <%= form.text_field :IP ,placeholder: 'Eg. 8.8.8.8' %>  
              </div>
                 <%= form.submit "Search" ,class:"btn btn-primary" %> 
                <% end %>
            </div>
          </div>
        
      </div>
    </div>
  </div>